#!/usr/bin/env bash

commit_msg="Backup: $(date +"%m-%d, %I:%M %p, %Y")"

repos=("notes" "personal" "faculdade")

for repo in "${repos[@]}"; do
    pushd "$HOME/$repo" || exit
    git add .
    git commit -m "$commit_msg"
    git push
    popd || exit
done
